const menuButton=document.querySelector('.menu-button');
const mobileNav=document.querySelector('#research-mobile-nav');
if(menuButton&&mobileNav){menuButton.addEventListener('click',()=>{const expanded=menuButton.getAttribute('aria-expanded')==='true';menuButton.setAttribute('aria-expanded',String(!expanded));mobileNav.hidden=expanded;});mobileNav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{mobileNav.hidden=true;menuButton.setAttribute('aria-expanded','false');}));}
function escapeHtml(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');}
function reportCard(report,mode){const seasons=Number(report.completedSeasons)||'—';const score=Number(report.finalScore).toFixed(1);const href=mode==='detail'?'#evidence':`../${escapeHtml(report.methodologyRoute)}`;const label=mode==='detail'?'View the Report 001 worked example below':'Open this report’s proof';return `<article><span>REPORT ${escapeHtml(report.number)} · ${escapeHtml(report.league||report.sport||'')}</span><strong>${escapeHtml(report.coreEvidenceRecords)}</strong><h3>${escapeHtml(report.subject)}</h3><p>${seasons} completed seasons · ${Number(report.randomWeightSimulations).toLocaleString()} random-weight tests · winner: ${escapeHtml(report.finalLeader)} (${score})</p><a href="${href}">${label} →</a></article>`;}

async function hydrateResearchHub(){
  // Shared by the hub and report-specific methodology pages. Only the hub has #evidence.
  if(!document.querySelector('#evidence'))return;
  try{
    const response=await fetch('../data/reports.json',{cache:'no-store'});if(!response.ok)return;
    const registry=await response.json();const published=(registry.reports||[]).filter(r=>r.status==='published').sort((a,b)=>String(a.number).localeCompare(String(b.number)));if(published.length<2)return;
    const colts=published.find(r=>r.slug==='colts'),lions=published.find(r=>r.slug==='lions'),pacers=published.find(r=>r.slug==='pacers');if(!colts||!lions)return;
    const totalEvidence=published.reduce((s,r)=>s+(Number(r.coreEvidenceRecords)||0),0),totalSimulations=published.reduce((s,r)=>s+(Number(r.randomWeightSimulations)||0),0),totalSeasons=published.reduce((s,r)=>s+(Number(r.completedSeasons)||0),0);
    const headerAction=document.querySelector('.site-header .header-action'),mobileAction=mobileNav?.querySelector('a:last-child');if(headerAction){headerAction.textContent='Explore stories';headerAction.href='../index.html#quick-verdict';}if(mobileAction){mobileAction.textContent='Explore stories';mobileAction.href='../index.html#quick-verdict';}
    const heroActions=document.querySelector('.research-hero .hero-actions');if(heroActions)heroActions.innerHTML='<a class="button primary" href="#quick">Show me the simple version</a><a class="button secondary" href="#report-proof">Choose a report’s proof</a>';
    const audit=document.querySelector('.audit-strip');if(audit){audit.setAttribute('aria-label','Era Theory published research audit summary');audit.innerHTML=`<div><strong>${totalSeasons}</strong><span>completed seasons studied</span></div><div><strong>${totalEvidence}</strong><span>core evidence records</span></div><div><strong>${totalEvidence} / ${totalEvidence}</strong><span>core records carry a source</span></div><div><strong>${totalSimulations.toLocaleString()}</strong><span>random-weight tests</span></div>`;}
    const quick=document.querySelector('#quick');if(quick&&!document.querySelector('#report-proof')){const chooser=document.createElement('section');chooser.className='research-section';chooser.id='report-proof';chooser.innerHTML=`<div class="research-heading"><p>Choose the proof you want</p><h2>Same evidence philosophy. Different sports questions.</h2></div><p class="research-intro">The Colts detail remains the first worked example below. Detroit and Indiana each have their own methodology because the unit of analysis and some scoring rules change with the question.</p><div class="result-proof report-proof-grid">${reportCard(colts,'detail')}${reportCard(lions,'separate')}${pacers?reportCard(pacers,'separate'):''}<article><span>ALL PUBLISHED REPORTS</span><strong>${totalEvidence}</strong><h3>Combined Era Theory research base</h3><p>${totalSeasons} completed seasons · ${totalSimulations.toLocaleString()} random-weight tests · ${totalEvidence}/${totalEvidence} core records source-linked.</p><a href="../index.html#reports">Choose a story →</a></article></div>`;quick.insertAdjacentElement('afterend',chooser);}
    const evidenceHeading=document.querySelector('#evidence .research-heading'),evidenceIntro=document.querySelector('#evidence .research-intro');if(evidenceHeading)evidenceHeading.innerHTML='<p>Report 001 worked example</p><h2>How deep did the Colts audit go?</h2>';if(evidenceIntro)evidenceIntro.innerHTML=`The ${colts.coreEvidenceRecords} count below is Report 001’s row-level evidence base. Detroit is a separate ${lions.coreEvidenceRecords}-record audit${pacers?`, and the Pacers conversion study is a separate ${pacers.coreEvidenceRecords}-record cross-sport audit`:''}.`;
    const modelIntro=document.querySelector('#model .research-intro');if(modelIntro)modelIntro.textContent='Reports share the discipline—explicit dimensions, locked weights, sourced row-level evidence and robustness testing—but they do not force different sports questions into one universal formula. Reports 001 and 002 use the same NFL model; Report 003 adapts the seven fan questions to NBA competitive cores and star conversion.';
    const resultProof=document.querySelector('#model .result-proof');if(resultProof)resultProof.innerHTML=published.map(r=>`<article><span>Report ${escapeHtml(r.number)} result</span><strong>${Number(r.finalScore).toFixed(1)}</strong><h3>${escapeHtml(r.finalLeader)}</h3><p>${escapeHtml(r.subject)} · ${escapeHtml(r.subtitle)}</p></article>`).join('');
    const counterexample=document.querySelector('.counterexample-box');if(counterexample)counterexample.innerHTML='<h3>Can a different definition change the winner?</h3><p>Sometimes. Indianapolis has deliberately narrow models where Ballard or Grigson can win; Detroit is unusually robust and Holmes survives every tested complete model; Indiana is in between—the Haliburton core wins every leave-one-dimension-out test and 91.6% of balanced random models, but the Paul George core wins a coherent resilience-heavy philosophy. Robustness is a result, not a predetermined requirement.</p>';
    const sourceHeading=document.querySelector('#sources .research-heading'),sourceIntro=document.querySelector('#sources .research-intro'),sourceLines=document.querySelector('#sources .source-lines');if(sourceHeading)sourceHeading.innerHTML='<p>Where does the information come from?</p><h2>Every published core evidence row has a source.</h2>';if(sourceIntro)sourceIntro.textContent='We prefer official or primary organizational sources, established historical/statistical databases and explicit attribution for every rights-reviewed photograph. Judgment calls stay labeled as judgment calls.';if(sourceLines)sourceLines.innerHTML=`<article><h3>NFL reports</h3><p>Official Colts/Lions transaction, coaching and organizational material plus Pro Football Reference/nflverse cross-checks.</p><a href="https://www.pro-football-reference.com/" target="_blank" rel="noreferrer">Open NFL historical database ↗</a></article><article><h3>NBA report</h3><p>Official NBA/Pacers trade, injury, honors and coaching material plus Basketball Reference season/efficiency history.</p><a href="https://www.basketball-reference.com/teams/IND/" target="_blank" rel="noreferrer">Open Pacers historical index ↗</a></article><article><h3>Authentic imagery</h3><p>Real people use rights-reviewed real photography with creator, license and modification records.</p><a href="../image-credits.html">See image credits & rights →</a></article>`;
    const privateWorkbook=document.querySelector('.private-workbook');if(privateWorkbook)privateWorkbook.innerHTML='<strong>Why aren’t the full research workbooks public?</strong><p>Each report’s organized native research workbook is kept private so the underlying research asset is not simply handed away. Public transparency comes from evidence inventories, formulas, source policies, exclusions, limitations and interactive sensitivity tests.</p>';
    const limitsHeading=document.querySelector('#limits .research-heading'),limitLines=document.querySelector('#limits .limit-lines');if(limitsHeading)limitsHeading.innerHTML='<p>What can’t these projects know?</p><h2>The framework has limits, and every report has to show them.</h2>';if(limitLines)limitLines.innerHTML=`<article><h3>No private team information</h3><p>We do not have internal scouting boards, medical files, ownership discussions or private coaching evaluations.</p></article><article><h3>Recent evidence needs time</h3><p>Young draft classes and unresolved acquisitions are tracked without forcing premature mature grades.</p></article><article><h3>Active/future seasons do not rewrite finished cutoffs</h3><p>Each report declares its own completed-season cutoff and only reopens the verdict when a later research update is deliberately run.</p></article><article><h3>Some categories require judgment</h3><p>Draft, transaction, system and adversity grades include evidence-coded judgment. Rules stay explicit so readers can disagree.</p></article><article><h3>Cross-sport models should not be identical</h3><p>An NFL front-office comparison and an NBA star-conversion study can share research discipline without pretending quarterback management and NBA star succession are the same thing.</p></article><article><h3>Stress tests are not truth probabilities</h3><p>Random-weight simulations measure ranking fragility when priorities change. They do not turn sports-history conclusions into objective probabilities.</p></article>`;
    const next=document.querySelector('.research-next');if(next)next.innerHTML='<div><p class="research-kicker">Ready to go back to the stories?</p><h2>The methodology should explain the argument—not replace it.</h2></div><a class="button primary" href="../index.html#quick-verdict">Choose a story</a>';
    const footer=document.querySelector('footer p');if(footer)footer.textContent=`Reports 001–${String(published.length).padStart(3,'0')} are published. ${totalEvidence}/${totalEvidence} core evidence records source-linked across the current Era Theory research base.`;
  }catch{/* keep server-rendered worked example */}
}
hydrateResearchHub();
