const button=document.querySelector('.menu-button');const nav=document.querySelector('#cubs-mobile-nav');button?.addEventListener('click',()=>{const expanded=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!expanded));nav.hidden=expanded});nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.hidden=true;button?.setAttribute('aria-expanded','false')}));
const presets={
  published:{label:'Published lifecycle model',score:80.7,className:'Championship lifecycle — not a dynasty',text:'The balanced lifecycle model rewards elite foundation building and peak quality while penalizing renewal, retention and incomplete postseason conversion beyond 2016.'},
  title:{label:'Title-first model',score:80.0,className:'Championship lifecycle — not a dynasty',text:'Giving the most weight to peak quality and October conversion still produces a strong championship lifecycle, but weighting cannot manufacture a second pennant or second title.'},
  dynasty:{label:'Dynasty-first / durability-heavy model',score:77.3,className:'Strong but incomplete lifecycle',text:'When durability and renewal matter more, the pitching pipeline and clustered contract-control problem become the dominant weakness.'},
  development:{label:'Talent-development-first model',score:78.5,className:'Strong but incomplete lifecycle',text:'The system developed many useful players, but mature draft performance and homegrown pitching renewal were not strong enough to sustain the original peak.'},
  recovery:{label:'Second-cycle-heavy model',score:79.3,className:'Strong but incomplete lifecycle',text:'The 2025 rebound strengthens the full lifecycle, but the second build was a hybrid construction rather than a direct continuation of the 2016 core.'}
};
const label=document.querySelector('#cubs-preset-label'),score=document.querySelector('#cubs-preset-score'),klass=document.querySelector('#cubs-preset-class'),explain=document.querySelector('#cubs-preset-explainer');document.querySelectorAll('[data-preset]').forEach(control=>control.addEventListener('click',()=>{const preset=presets[control.dataset.preset];if(!preset)return;document.querySelectorAll('[data-preset]').forEach(btn=>btn.classList.toggle('active',btn===control));if(label)label.textContent=preset.label;if(score)score.textContent=preset.score.toFixed(1);if(klass)klass.textContent=preset.className;if(explain)explain.textContent=preset.text}));
