const button=document.querySelector('.menu-button');const nav=document.querySelector('#cubs-mobile-nav');button?.addEventListener('click',()=>{const expanded=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!expanded));nav.hidden=expanded});nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.hidden=true;button?.setAttribute('aria-expanded','false')}));
const presets={
  published:{label:'Published lifecycle model',score:82.0,className:'Successful with flaws',text:'The balanced lifecycle model rewards the elite build and championship conversion while preserving real penalties for late-window efficiency, exit timing and the mixed teardown return.'},
  title:{label:'Title-first fan',score:83.8,className:'Successful with flaws',text:'Putting 40% of the model on postseason conversion raises the score, but the exit timing and mixed teardown still matter.'},
  dynasty:{label:'Exit-timing skeptic',score:77.3,className:'Successful with flaws',text:'Giving decline detection and exit timing the largest weight produces the harshest timing-focused grade, but the full lifecycle still clears the successful threshold.'},
  development:{label:'Asset-efficiency skeptic',score:77.0,className:'Successful with flaws',text:'Heavy emphasis on window resource efficiency and teardown returns exposes the weakest parts of the cycle without erasing the elite build or championship.'},
  recovery:{label:'Rebuild-conversion fan',score:78.6,className:'Successful with flaws',text:'Prioritizing teardown and next-window conversion rewards the 2025 return to contention but also penalizes how little of that roster came directly from the 2021 haul.'}
};
const label=document.querySelector('#cubs-preset-label'),score=document.querySelector('#cubs-preset-score'),klass=document.querySelector('#cubs-preset-class'),explain=document.querySelector('#cubs-preset-explainer');document.querySelectorAll('[data-preset]').forEach(control=>control.addEventListener('click',()=>{const preset=presets[control.dataset.preset];if(!preset)return;document.querySelectorAll('[data-preset]').forEach(btn=>btn.classList.toggle('active',btn===control));if(label)label.textContent=preset.label;if(score)score.textContent=preset.score.toFixed(1);if(klass)klass.textContent=preset.className;if(explain)explain.textContent=preset.text}));
