const button=document.querySelector('.menu-button');const nav=document.querySelector('#cubs-mobile-nav');button?.addEventListener('click',()=>{const expanded=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!expanded));nav.hidden=expanded});nav?.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.hidden=true;button?.setAttribute('aria-expanded','false')}));
const presets={
  published:{label:'Published lifecycle model',score:83.7,className:'Historic championship window — not a dynasty',text:'The balanced lifecycle model rewards elite foundation building, a historically great peak and strong asset conversion while penalizing the failure to replenish and extend championship-level quality.'},
  title:{label:'Title-first model',score:83.1,className:'Championship-successful lifecycle',text:'Prioritizing the ring and October conversion keeps the lifecycle firmly successful, but weighting cannot create a second pennant or second championship.'},
  dynasty:{label:'Dynasty-first model',score:80.7,className:'Championship-successful lifecycle — historical dynasty gate still fails',text:'Even a dynasty-oriented weighting keeps the lifecycle above 80, but the historical gate remains separate: one pennant and one title are not repeated championship conversion.'},
  development:{label:'Sustainability-first model',score:77.6,className:'Strong but incomplete lifecycle',text:'When replenishment and long-term control matter most, the 2016–20 development drop-off and clustered contract cliff become the decisive weaknesses.'},
  recovery:{label:'Recovery-first model',score:81.3,className:'Championship-successful lifecycle',text:'The 2025 rebound strengthens the full lifecycle, but the second build was a hybrid new cycle rather than uninterrupted continuation of the 2016 window.'}
};
const label=document.querySelector('#cubs-preset-label'),score=document.querySelector('#cubs-preset-score'),klass=document.querySelector('#cubs-preset-class'),explain=document.querySelector('#cubs-preset-explainer');document.querySelectorAll('[data-preset]').forEach(control=>control.addEventListener('click',()=>{const preset=presets[control.dataset.preset];if(!preset)return;document.querySelectorAll('[data-preset]').forEach(btn=>btn.classList.toggle('active',btn===control));if(label)label.textContent=preset.label;if(score)score.textContent=preset.score.toFixed(1);if(klass)klass.textContent=preset.className;if(explain)explain.textContent=preset.text}));
