import { readFile, stat } from 'node:fs/promises';
import { resolve } from 'node:path';
const root=resolve(import.meta.dirname,'..');const dist=resolve(root,'dist');
const report=await readFile(resolve(dist,'reports','cubs','index.html'),'utf8');
const method=await readFile(resolve(dist,'research','cubs','index.html'),'utf8');
const registry=JSON.parse(await readFile(resolve(dist,'data','reports.json'),'utf8'));
const manifest=JSON.parse(await readFile(resolve(dist,'assets','archive','cubs-manifest.json'),'utf8'));
const credits=await readFile(resolve(dist,'image-credits.html'),'utf8');
const rights=await readFile(resolve(root,'ERA_THEORY_IMAGE_RIGHTS_LEDGER.csv'),'utf8');
const home=await readFile(resolve(dist,'index.html'),'utf8');
const homeJs=await readFile(resolve(dist,'home.js'),'utf8');
const crossSportJs=await readFile(resolve(dist,'report-004-site.js'),'utf8');
const published=(registry.reports||[]).filter(r=>r.status==='published').sort((a,b)=>String(a.number).localeCompare(String(b.number)));
const cubs=published.find(r=>r.number==='004'&&r.slug==='cubs');if(!cubs)throw new Error('Report 004 missing from published registry.');
if(published.length!==4)throw new Error(`Expected 4 published reports, found ${published.length}.`);
const totals={seasons:published.reduce((s,r)=>s+(Number(r.completedSeasons)||0),0),evidence:published.reduce((s,r)=>s+(Number(r.coreEvidenceRecords)||0),0),tests:published.reduce((s,r)=>s+(Number(r.randomWeightSimulations)||0),0)};
if(totals.seasons!==83||totals.evidence!==1043||totals.tests!==1200000)throw new Error(`Unexpected four-report totals: ${JSON.stringify(totals)}`);
if(cubs.finalScore!==82||cubs.coreEvidenceRecords!==139||cubs.dimensions!==7)throw new Error(`Unexpected Cubs frozen registry: score ${cubs.finalScore}, evidence ${cubs.coreEvidenceRecords}, dimensions ${cubs.dimensions}.`);
for(const marker of ['Mostly yes—but probably one offseason late.','82.0','Successful with flaws','The teardown helped. It did not build the next contender by itself.','139 / 139','15.5%','69.0%','60.4','99.895%'])if(!report.includes(marker))throw new Error(`Cubs report missing frozen marker: ${marker}`);
for(const marker of ['139 / 139','Seven MLB lifecycle questions','300,000 random-weight tests','99.895%','0 / 100,000','Re-entry is only one complete season','139 of 139 core records carry a source'])if(!method.includes(marker))throw new Error(`Cubs methodology missing frozen marker: ${marker}`);
for(const stale of ['83.7','186 / 186','186 sourced records','80.7','135 / 135','135 sourced records','Eight MLB lifecycle questions','A great championship window. Not a dynasty.','Did the Cubs build a dynasty—or one great championship window?','Championship lifecycle — not a dynasty'])if(report.includes(stale)||method.includes(stale))throw new Error(`Stale Report 004 marker survived build: ${stale}`);
if(/docs\.google\.com\/spreadsheets/i.test(report+method))throw new Error('Private Google Sheet URL leaked into public Cubs HTML.');
if(!Array.isArray(manifest.assets)||manifest.assets.length!==6)throw new Error(`Expected 6 archived Cubs images, found ${manifest.assets?.length||0}.`);
for(const asset of manifest.assets){if(asset.status!=='approved')throw new Error(`Non-approved Cubs asset: ${asset.id}`);if(!asset.localSrc?.startsWith('/assets/archive/'))throw new Error(`Cubs asset ${asset.id} lacks local source.`);await stat(resolve(dist,asset.localSrc.replace(/^\//,'')));for(const value of [asset.id,asset.creator,asset.sourcePage,asset.license,asset.changes])if(!credits.includes(value))throw new Error(`Image credits missing ${asset.id} rights metadata: ${value}`);if(!rights.includes(asset.id)||!rights.includes(asset.sourcePage))throw new Error(`Permanent rights ledger missing Cubs asset ${asset.id}.`);if(!report.includes(asset.localSrc))throw new Error(`Cubs report does not use ${asset.localSrc}.`)}
if(!home.includes('Did the Cubs break up the 2016 core at the right time?'))throw new Error('Server-rendered homepage fallback missing frozen Report 004 question.');
for(const marker of ['completedSeasons','published.map(renderStoryLane)','completed seasons studied'])if(!homeJs.includes(marker))throw new Error(`Homepage registry renderer missing marker: ${marker}`);
for(const marker of ['CUBS','seven-dimension MLB championship-window lifecycle model','NFL, NBA and MLB','cubs/index.html'])if(!crossSportJs.includes(marker))throw new Error(`Report 004 cross-sport enhancement missing marker: ${marker}`);
if(!home.includes('/report-004-site.js'))throw new Error('Homepage does not load Report 004 cross-sport enhancement.');
if(!report.includes('Real people, real photographs.'))throw new Error('Cubs authentic-image disclosure missing.');
console.log(`Verified frozen Report 004: ${published.length} published stories, ${totals.seasons} completed seasons, ${totals.evidence}/${totals.evidence} sourced core records, ${totals.tests.toLocaleString()} model tests and ${manifest.assets.length} rights-ledgered Cubs photographs.`);
