import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';
const root=resolve(import.meta.dirname,'..');const dist=resolve(root,'dist');
const report=await readFile(resolve(dist,'reports','pacers','index.html'),'utf8');
const method=await readFile(resolve(dist,'research','pacers','index.html'),'utf8');
const registry=JSON.parse(await readFile(resolve(dist,'data','reports.json'),'utf8'));
const manifest=JSON.parse(await readFile(resolve(dist,'assets','archive','pacers-manifest.json'),'utf8'));
const credits=await readFile(resolve(dist,'image-credits.html'),'utf8');
const home=await readFile(resolve(dist,'index.html'),'utf8');
const homeJs=await readFile(resolve(dist,'home.js'),'utf8');
const researchJs=await readFile(resolve(dist,'research','research.js'),'utf8');
const rights=await readFile(resolve(root,'ERA_THEORY_IMAGE_RIGHTS_LEDGER.csv'),'utf8');
const published=(registry.reports||[]).filter(r=>r.status==='published').sort((a,b)=>String(a.number).localeCompare(String(b.number)));
const pacers=published.find(r=>r.number==='003'&&r.slug==='pacers');
if(!pacers)throw new Error('Report 003 missing from published registry.');
if(published.length<3)throw new Error(`Report 003 requires at least 3 published reports; found ${published.length}.`);
const totals={seasons:published.reduce((s,r)=>s+(Number(r.completedSeasons)||0),0),evidence:published.reduce((s,r)=>s+(Number(r.coreEvidenceRecords)||0),0),tests:published.reduce((s,r)=>s+(Number(r.randomWeightSimulations)||0),0)};
if(totals.seasons<69||totals.evidence<904||totals.tests<900000)throw new Error(`Published library regressed below Report 003 baseline: ${JSON.stringify(totals)}`);
for(const marker of ['The Haliburton core wins','83.6','79.3','59.9','One asset chain kept changing shape','Can the Paul George core still win?','175 sourced records','300,000 random-weight tests']) if(!report.includes(marker))throw new Error(`Pacers report missing marker: ${marker}`);
for(const marker of ['175 / 175','Eight NBA questions','58.4%','64.2%','Zubac trade is unresolved']) if(!method.includes(marker))throw new Error(`Pacers methodology missing marker: ${marker}`);
if(/docs\.google\.com\/spreadsheets/i.test(report+method))throw new Error('Private Google Sheet URL leaked into public Pacers HTML.');
if(!Array.isArray(manifest.assets)||manifest.assets.length!==5)throw new Error(`Expected 5 archived Pacers images, found ${manifest.assets?.length||0}.`);
for(const asset of manifest.assets){
  if(asset.status!=='approved')throw new Error(`Non-approved Pacers archive asset: ${asset.id}`);
  if(!asset.localSrc?.startsWith('/assets/archive/'))throw new Error(`Pacers asset ${asset.id} missing local archive path.`);
  for(const value of [asset.id,asset.creator,asset.sourcePage,asset.license,asset.changes])if(!credits.includes(value))throw new Error(`Image credits missing ${asset.id} rights metadata: ${value}`);
  if(!report.includes(asset.localSrc))throw new Error(`Pacers report does not use archived asset ${asset.localSrc}.`);
  if(!rights.includes(asset.id)||!rights.includes(asset.sourcePage))throw new Error(`Permanent rights ledger missing Pacers asset ${asset.id}.`);
}
if(!home.includes('How did the Pacers keep turning one star into the next?'))throw new Error('Server-rendered homepage fallback missing Report 003.');
for(const marker of ['completedSeasons','published.map(renderStoryLane)','completed seasons studied'])if(!homeJs.includes(marker))throw new Error(`Cross-sport homepage code missing marker: ${marker}`);
for(const marker of ['completedSeasons','eight-dimension NBA','published.map'])if(!researchJs.includes(marker))throw new Error(`Cross-sport research hub code missing marker: ${marker}`);
if(!report.includes('Real people, real photographs.'))throw new Error('Pacers authentic-image disclosure missing.');
console.log(`Verified Report 003 remains intact inside a ${published.length}-story library: 175 sourced Pacers records, 300,000 Pacers model tests, ${manifest.assets.length} rights-ledgered photographs and no private-workbook leak.`);
