const button = document.querySelector('.menu-button');
const nav = document.querySelector('#home-mobile-nav');
button?.addEventListener('click', () => { const expanded = button.getAttribute('aria-expanded') === 'true'; button.setAttribute('aria-expanded', String(!expanded)); nav.hidden = expanded; });
nav?.querySelectorAll('a').forEach(link => link.addEventListener('click', () => { nav.hidden = true; button?.setAttribute('aria-expanded','false'); }));

function escapeHtml(value){return String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function renderPublishedTile(report,index){const meta=`${report.league||report.sport||'SPORT'} · ${report.scoringCutoff||'Published'}`.toUpperCase();const score=Number.isFinite(Number(report.finalScore))?Number(report.finalScore).toFixed(1):'—';return `<article class="report-tile ${index===0?'featured':''}"><div class="report-number">${escapeHtml(report.number)}</div><div class="report-tile-body"><p>${escapeHtml(meta)}</p><h3>${escapeHtml(report.publicQuestion||report.title)}</h3><span>${escapeHtml(report.subtitle||report.subject||'')}</span><p>${escapeHtml(report.summary||report.fanSummary||'')}</p></div><div class="report-tile-result"><strong>${score}</strong><small>${escapeHtml(report.resultLabel||'Final score')}</small><a href="${escapeHtml(report.route)}">Start the story</a></div></article>`}
function renderPlannedTile(number){return `<article class="report-tile planned"><div class="report-number">${escapeHtml(number)}</div><div class="report-tile-body"><p>NEXT STORY · NOT YET SELECTED</p><h3>Another sports argument, researched from scratch.</h3><span>The next subject comes after the current stories are audited as one site.</span><p>Era Theory keeps the evidence standard but adapts the question and scoring to the sport.</p></div><div class="report-tile-result"><strong>—</strong><small>Not researched</small><span>Coming later</span></div></article>`}
const beltTheoryTile=`<article class="report-tile concept"><div class="report-number">BT</div><div class="report-tile-body"><p>WRESTLING · COMPANION PROJECT</p><h3>Like wrestling history too?</h3><span>Belt Theory</span><p>Championship history and promotion eras researched with the same evidence-first philosophy.</p></div><div class="report-tile-result"><strong>↗</strong><small>Companion project</small><span>Independent</span></div></article>`;
function getReport(published,slug){return published.find(report=>report.slug===slug)}
function renderStoryLane(report){const score=Number.isFinite(Number(report.finalScore))?Number(report.finalScore).toFixed(1):'—';return `<article class="verdict-lane"><div><span>Report ${escapeHtml(report.number)}</span><strong>${score}</strong></div><h3>${escapeHtml(report.subject||report.title)}</h3><p><b>${escapeHtml(report.publicQuestion||report.title)}</b> ${escapeHtml(report.fanSummary||report.summary||'')}</p><small>Winner: ${escapeHtml(report.finalLeader||'See report')} · <a href="${escapeHtml(report.route)}">Start the story →</a></small></article>`}
function updateProofTotals(published){const proof=document.querySelector('.proof-after-story');if(!proof)return;const seasons=published.reduce((sum,r)=>sum+(Number(r.completedSeasons)||0),0);const evidence=published.reduce((sum,r)=>sum+(Number(r.coreEvidenceRecords)||0),0);const simulations=published.reduce((sum,r)=>sum+(Number(r.randomWeightSimulations)||0),0);proof.innerHTML=`<div><strong>${seasons}</strong><span>completed seasons studied</span></div><div><strong>${evidence}</strong><span>core evidence records</span></div><div><strong>${simulations.toLocaleString()}</strong><span>model stress tests</span></div><div><strong>${evidence} / ${evidence}</strong><span>core records source-linked</span></div>`;const explainer=document.querySelector('.proof-explainer');if(explainer)explainer.innerHTML='<strong>Why these numbers are down here:</strong> the research supports the stories. Fans should understand the argument first and only enter the audit trail when they want it.'}
function hydrateHomeIntro(published){if(!published.length)return;const colts=getReport(published,'colts'),lions=getReport(published,'lions'),pacers=getReport(published,'pacers');const kicker=document.querySelector('.fan-kicker'),title=document.querySelector('#home-title'),lede=document.querySelector('.fan-lede'),heroActions=document.querySelector('.fan-hero .hero-actions'),note=document.querySelector('.authentic-note'),headerAction=document.querySelector('.site-header .header-action'),mobileAction=nav?.querySelector('a:last-child');if(kicker)kicker.textContent='ERA THEORY · SPORTS STORIES · FULL CONTEXT';if(title)title.textContent='Sports debates, researched all the way through.';if(lede)lede.textContent='Pick a story. Era Theory researches the full competitive cycle—results, stars, drafts, trades, coaching, roster construction and adversity—then guides you through what actually changed in plain English.';if(heroActions)heroActions.innerHTML='<a class="button primary" href="#quick-verdict">Choose a story</a><a class="button secondary" href="#how-it-works">How it works</a>';const leagues=[...new Set(published.map(r=>r.league).filter(Boolean))];if(note)note.innerHTML=`<strong>Real history, real photography.</strong> Era Theory now has ${published.length} published stories across ${leagues.join(' and ')}. Real people use rights-reviewed source photography, never AI stand-ins.`;for(const action of [headerAction,mobileAction])if(action){action.textContent='Explore stories';action.setAttribute('href','#quick-verdict')}
const quickHeading=document.querySelector('.quick-verdict-heading'),lanes=document.querySelector('.verdict-lanes'),quickLink=document.querySelector('.quick-verdict > .text-link');if(quickHeading)quickHeading.innerHTML=`<p>Choose a story</p><h2 id="verdict-title">${published.length} sports stories. Different questions. Same evidence-first standard.</h2><p>You do not need to learn the model first. Pick the argument you care about and the report will walk you through the answer.</p>`;if(lanes)lanes.innerHTML=published.map(renderStoryLane).join('');if(quickLink){quickLink.textContent='See the full story library →';quickLink.setAttribute('href','#reports')}
const guide=document.querySelector('.story-guide');if(guide){const heading=guide.querySelector('.section-heading'),rail=guide.querySelector('.story-question-rail');if(heading)heading.innerHTML='<div><p>Start with the fan question</p><h2 id="guide-title">You should always know what you are learning next.</h2></div><p class="section-intro">Every report starts with the quick answer, then recognizable people, decisions and moments, before exposing the technical proof.</p>';const questions=[];if(colts)questions.push([colts.route+'#polian','COLTS','Was Polian really just Peyton?'],[colts.route+'#ballard','COLTS',"Why didn't Ballard's talent become wins?"]);if(lions)questions.push([lions.route+'#millen','LIONS','How bad was Millen really?'],[lions.route+'#holmes','LIONS','What did Holmes actually fix?']);if(pacers)questions.push([pacers.route+'#trade2017','PACERS','Was the Paul George trade really a win?'],[pacers.route+'#resilience','PACERS','How dependent is Indiana on Haliburton?']);if(rail)rail.innerHTML=questions.map(([href,label,text])=>`<a href="${escapeHtml(href)}"><b>${label}</b><span>${escapeHtml(text)}</span></a>`).join('')}
updateProofTotals(published);const footerCopy=document.querySelector('footer p');if(footerCopy)footerCopy.textContent='Era Theory publishes completed, source-backed sports stories across leagues. Real people and historical moments use authentic source photography.'}
async function hydrateHomepage(){const library=document.querySelector('.report-library');try{const response=await fetch('data/reports.json',{cache:'no-store'});if(!response.ok)return;const registry=await response.json();const published=(registry.reports||[]).filter(r=>r.status==='published').sort((a,b)=>String(a.number).localeCompare(String(b.number)));if(!published.length)return;hydrateHomeIntro(published);if(library){const highest=Math.max(...published.map(r=>Number(r.number)||0));library.innerHTML=`${published.map(renderPublishedTile).join('')}${renderPlannedTile(String(highest+1).padStart(3,'0'))}${beltTheoryTile}`}}catch{}}
const hydrateReportLibrary=hydrateHomepage;hydrateReportLibrary();
